
export const actionConstants =
{
    // || LOGIN CONSTANTS ||
    SET_WHATSAPP_NUMBER: 'SET_WHATSAPP_NUMBER',



    // || CLIENT CONSTANTS ||

    OPEN_SIDENAV: 'OPEN_SIDENAV',
    CLOSE_SIDENAV: 'CLOSE_SIDENAV',
    OPEN_HOME_SEARCH: 'OPEN_HOME_SEARCH',
    CLOSE_HOME_SEARCH: 'CLOSE_HOME_SEARCH',
    OPEN_FILTER: 'OPEN_FILTER',
    CLOSE_FILTER: 'CLOSE_FILTER',
    OPEN_CUSTOMIZATION: 'OPEN_CUSTOMIZATION',
    CLOSE_CUSTOMIZATION: 'CLOSE_CUSTOMIZATION',
    OPEN_MESSAGE: 'OPEN_MESSAGE',
    CLOSE_MESSAGE: 'CLOSE_MESSAGE',

    // CART CONSTANTS
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
    UPDATE_TAXED_PRICE: 'UPDATE_TAXED_PRICE',
    CREATE_CHECKOUT: 'CREATE_CHECKOUT',
    DELETE_CHECKOUT: 'DELETE_CHECKOUT',
    EMPTY_CART: 'EMPTY_CART',
    UPDATE_CHECKOUT_BILLING_ADDRESS: 'UPDATE_CHECKOUT_BILLING_ADDRESS',
    UPDATE_CHECKOUT_SHIPPING_ADDRESS: 'UPDATE_CHECKOUT_SHIPPING_ADDRESS',




    // GRAPH CONSTANTS
    SET_ESSENTIALS: 'SET_ESSENTIALS',
    FETCH_STORE_DETAILS: 'FETCH_STORE_DETAILS',
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    FETCH_COUNTRIES: 'FETCH_COUNTRIES',
    HANDLE_FILTERS: 'HANDLE_FILTERS',

}